#!/usr/bin/env node

/**
 * Prisma-to-JPA Generator
 *
 * Reads a Prisma schema file and generates JPA @Entity Java classes.
 *
 * Usage:
 *   node prisma-to-jpa.mjs --schema <path> --out <output-dir> --package <java.package.name>
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ─────────────────────────────────────────────────────────────────────────────
// Type Mapping
// ─────────────────────────────────────────────────────────────────────────────

const TYPE_MAP = {
  'String': 'String',
  'Boolean': 'Boolean',
  'Int': 'Integer',
  'BigInt': 'Long',
  'Float': 'Double',
  'Decimal': 'java.math.BigDecimal',
  'DateTime': 'java.time.Instant',
  'UUID': 'java.util.UUID',
  'Json': 'com.fasterxml.jackson.databind.JsonNode',
  'Bytes': 'byte[]',
};

/**
 * Maps a Prisma type to its Java/JPA equivalent.
 * Returns null if the type is an enum (enums are handled separately).
 */
function mapType(prismaType) {
  // Strip optional (?) and array ([]) notation
  const baseType = prismaType.replace(/\?$/, '').replace('[]', '');
  return TYPE_MAP[baseType] || null; // null signals enum
}

// ─────────────────────────────────────────────────────────────────────────────
// Schema Parsing
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extracts the schema content, handling block comments.
 */
function extractSchemaContent(content) {
  // Remove line comments
  let result = content
    .replace(/\/\/.*$/gm, '')
    // Handle block comments (including multi-line ones)
    .replace(/\/\*[\s\S]*?\*\//g, '');

  return result;
}

/**
 * Parses a Prisma schema and returns an array of model objects.
 */
function parseSchema(content) {
  const schemaContent = extractSchemaContent(content);
  const models = [];

  // First, extract all model names to identify relations later
  const modelNames = new Set();
  const modelNameRegex = /^model\s+(\w+)\s*\{/gm;
  let nameMatch;
  while ((nameMatch = modelNameRegex.exec(schemaContent)) !== null) {
    modelNames.add(nameMatch[1]);
  }

  // Match model blocks: model ModelName { ... }
  const modelRegex = /^model\s+(\w+)\s*\{([\s\S]*?)\n\}/gm;

  let match;
  while ((match = modelRegex.exec(schemaContent)) !== null) {
    const modelName = match[1];
    const modelBody = match[2];
    const fields = parseFields(modelBody, modelNames);
    const tableName = toSnakeCase(modelName);

    models.push({ name: modelName, tableName, fields });
  }

  return models;
}

/**
 * Parses field definitions within a model body.
 */
function parseFields(body, modelNames) {
  const fields = [];
  const lines = body.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;

    // Skip block-level decorators like @@index, @@unique, @@id, etc.
    if (trimmed.startsWith('@@')) continue;

    // Skip relation fields (types that reference other models, not scalars or enums)
    // These are relations like "tenant Tenant @relation(...)" or "employees Employee[]"
    const relationMatch = trimmed.match(/^(\w+)\s+(\w+[\[\]?]?)\s+@relation/);
    if (relationMatch) continue;
    const arrayRelationMatch = trimmed.match(/^(\w+)\s+(\w+[\[\]?]?)\s*$/);
    if (arrayRelationMatch && modelNames.has(arrayRelationMatch[2].replace(/\[\]$/, '').replace(/\?$/, ''))) {
      // Check if this is actually a relation field (type is a model name)
      const possibleType = arrayRelationMatch[2].replace(/\[\]$/, '').replace(/\?$/, '');
      if (modelNames.has(possibleType) && !TYPE_MAP[possibleType] && !possibleType.startsWith('Enum')) {
        continue;
      }
    }

    // Parse field: fieldName Type? @decorators
    const fieldMatch = trimmed.match(/^(\w+)\s+(\w+[\[\]?]?)\s*(.*)?$/);
    if (!fieldMatch) continue;

    const fieldName = fieldMatch[1];
    const fieldType = fieldMatch[2];
    const decoratorsStr = fieldMatch[3] || '';

    // Skip if type is a model name (relation field without @relation decorator)
    const baseType = fieldType.replace(/\[\]$/, '').replace(/\?$/, '');
    if (modelNames.has(baseType) && !TYPE_MAP[baseType]) {
      continue;
    }

    const field = {
      name: fieldName,
      columnName: toSnakeCase(fieldName),
      prismaType: fieldType,
      javaType: mapType(fieldType),
      isEnum: mapType(fieldType) === null,
      isId: false,
      isUnique: false,
      isList: fieldType.endsWith('[]'),
      isOptional: fieldType.endsWith('?'),
      hasDefault: false,
      defaultValue: null,
      isAutoGenerated: false,
      isTimestamp: false,
      isUpdatedAt: false,
      isCreatedAt: false,
    };

    // Parse decorators
    const decorators = decoratorsStr.match(/@\w+(\([^)]*\))?/g) || [];
    for (const decorator of decorators) {
      const nameMatch = decorator.match(/^@(\w+)/);
      if (!nameMatch) continue;
      const decoratorName = nameMatch[1];

      // Extract parameters if present
      let params = {};
      const paramsMatch = decorator.match(/\(([^)]*)\)/);
      if (paramsMatch) {
        const paramStr = paramsMatch[1];
        // Parse key=value pairs
        const kvMatches = paramStr.matchAll(/(\w+)\s*=\s*("[^"]*"|\w+)/g);
        for (const [, k, v] of kvMatches) {
          params[k] = v.replace(/"/g, '');
        }
      }

      switch (decoratorName) {
        case 'id':
          field.isId = true;
          break;
        case 'unique':
          field.isUnique = true;
          break;
        case 'default':
          field.hasDefault = true;
          field.defaultValue = params.value || params;
          // Check for auto-generation strategies
          if (field.isId && (params.value === 'cuid()' || params.value === 'uuid()' || field.prismaType === 'String')) {
            field.isAutoGenerated = 'UUID';
          } else if (params.value === 'now()') {
            field.isTimestamp = true;
          }
          break;
        case 'map':
          if (params.column) {
            field.columnName = params.column;
          }
          break;
        case 'updatedAt':
          field.isUpdatedAt = true;
          field.isTimestamp = true;
          break;
        case 'createdAt':
          field.isCreatedAt = true;
          field.isTimestamp = true;
          break;
      }
    }

    // Infer auto-generation for @id with cuid/uuid default
    if (field.isId && field.hasDefault && !field.isAutoGenerated) {
      const dv = typeof field.defaultValue === 'string' ? field.defaultValue : JSON.stringify(field.defaultValue);
      if (dv === '"cuid()"' || dv === '"uuid()"') {
        field.isAutoGenerated = 'UUID';
      }
    }

    fields.push(field);
  }

  return fields;
}

// ─────────────────────────────────────────────────────────────────────────────
// Naming Conventions
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Converts camelCase to snake_case
 */
function toSnakeCase(name) {
  return name
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

/**
 * Converts PascalCase to camelCase (for JavaBean property names)
 */
function toCamelCase(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

// ─────────────────────────────────────────────────────────────────────────────
// Code Generation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates the Java entity code for a model.
 */
function generateEntity(model, packageName) {
  const { name: modelName, tableName, fields } = model;

  const importLines = new Set([
    'jakarta.persistence.*',
    'lombok.*',
    'java.time.Instant',
    'java.util.UUID',
  ]);

  // Add BigDecimal if needed
  if (fields.some(f => f.javaType === 'java.math.BigDecimal')) {
    importLines.add('java.math.BigDecimal');
  }

  // Add JsonNode if needed
  if (fields.some(f => f.javaType === 'com.fasterxml.jackson.databind.JsonNode')) {
    importLines.add('com.fasterxml.jackson.databind.JsonNode');
  }

  // Add enum imports
  const enumFields = fields.filter(f => f.isEnum);
  if (enumFields.length > 0) {
    importLines.add(`${packageName}.enums.*`);
  }

  const importBlock = [...importLines]
    .sort()
    .map(i => `import ${i};`)
    .join('\n');

  const fieldLines = [];
  const separateTimestampFields = [];

  for (const field of fields) {
    // Skip separate timestamp fields that are managed by @CreationTimestamp/@UpdateTimestamp
    if (field.isTimestamp && !field.isId) {
      separateTimestampFields.push(field);
      continue;
    }

    const javaType = field.isEnum ? 'String' : field.javaType;
    const jpaAnnotations = [];
    const columnAnnotations = [];

    // @Id
    if (field.isId) {
      if (field.isAutoGenerated === 'UUID') {
        jpaAnnotations.push('@Id\n    @GeneratedValue(strategy = GenerationType.UUID)');
      } else {
        jpaAnnotations.push('@Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)');
      }
    }

    // @Column
    const colProps = [];
    if (field.columnName !== toCamelCase(field.name)) {
      colProps.push(`name = "${field.columnName}"`);
    }
    if (field.isUnique) {
      colProps.push('unique = true');
    }
    if (field.javaType === 'String' && !field.isId) {
      colProps.push('length = 191');
    }
    if (field.isOptional) {
      colProps.push('nullable = true');
    }

    if (colProps.length > 0) {
      columnAnnotations.push(`@Column(${colProps.join(', ')})`);
    }

    // @CreationTimestamp and @UpdateTimestamp
    if (field.isUpdatedAt) {
      jpaAnnotations.push('@UpdateTimestamp');
    }
    if (field.isCreatedAt && !field.hasDefault) {
      jpaAnnotations.push('@CreationTimestamp');
    }

    const finalAnnotations = [...jpaAnnotations, ...columnAnnotations]
      .filter(Boolean)
      .join('\n    ');

    const visibility = field.isId ? 'private ' : 'private ';
    fieldLines.push(`    ${finalAnnotations ? finalAnnotations + '\n    ' : ''}${visibility}${javaType} ${field.name};`);
  }

  // Add timestamp fields at the end
  for (const tsField of separateTimestampFields) {
    const javaType = 'Instant';
    const colProps = [];
    if (tsField.columnName !== toCamelCase(tsField.name)) {
      colProps.push(`name = "${tsField.columnName}"`);
    }
    colProps.push('nullable = true');

    const colAnnotation = `@Column(${colProps.join(', ')})`;
    fieldLines.push(`    ${colAnnotation}\n    private ${javaType} ${tsField.name};`);
  }

  const fieldsBlock = fieldLines.join('\n\n');

  return `package ${packageName};

${importBlock}

@Entity
@Table(name = "${tableName}")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ${modelName} {
${fieldsBlock}
}
`;
}

/**
 * Writes a Java file to the output directory.
 */
function writeJavaFile(outputDir, packageName, modelName, content) {
  const packagePath = packageName.replace(/\./g, '/');
  const dir = join(outputDir, packagePath);
  const filePath = join(dir, `${modelName}.java`);

  mkdirSync(dir, { recursive: true });
  writeFileSync(filePath, content, 'utf-8');

  return filePath;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  // Parse command line arguments
  const args = process.argv.slice(2);
  const options = {};

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--schema' && args[i + 1]) {
      options.schema = args[++i];
    } else if (args[i] === '--out' && args[i + 1]) {
      options.out = args[++i];
    } else if (args[i] === '--package' && args[i + 1]) {
      options.package = args[++i];
    }
  }

  if (!options.schema || !options.out || !options.package) {
    console.error('Usage: node prisma-to-jpa.mjs --schema <path> --out <output-dir> --package <java.package.name>');
    console.error('');
    console.error('Example:');
    console.error('  node prisma-to-jpa.mjs \\');
    console.error('    --schema apps/HRM-unified/prisma/schema.prisma \\');
    console.error('    --out backend-java/module-hrm/src/main/java \\');
    console.error('    --package com.vieterp.hrm.domain');
    process.exit(1);
  }

  // Read schema file
  if (!existsSync(options.schema)) {
    console.error(`Error: Schema file not found: ${options.schema}`);
    process.exit(1);
  }

  const schemaContent = readFileSync(options.schema, 'utf-8');
  const models = parseSchema(schemaContent);

  console.log(`Parsed ${models.length} models from ${options.schema}`);

  // Generate and write entity files
  let generated = 0;
  for (const model of models) {
    const javaCode = generateEntity(model, options.package);
    const filePath = writeJavaFile(options.out, options.package, model.name, javaCode);
    console.log(`Generated: ${filePath}`);
    generated++;
  }

  console.log(`\nDone! Generated ${generated} JPA entities.`);
}

main();